[project]
name = "polycoinpy"
version = "0.0.1"
description = "Placeholder package for future crypto library"
authors = [{ name = "sato" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
